import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className="page">
      <Head>
        <title>Senior Front-end Developer - Jonas Guedes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1"></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        <main className={styles.main}>
          <div className={styles.grid}>
            <div className={styles.image}>
              <div className={styles.imageBox}>
                <img src="/images/jonas.jpg" alt="Jonas Guedes" />
                {/* <img src="/images/jonas-avatar.png" alt="Jonas Guedes" title="Jonas Guedes" /> */}
              </div>
            </div>
            <div className={styles.about}>
              <ul className={styles.icons}>
                {/* <li><span>Redes Sociais</span></li> */}
                <li><a href="#" className="dribbble"><i className="bi bi-dribbble"></i></a></li>
                <li><a href="#" className="linkedin"><i className="bi bi-linkedin"></i></a></li>
                <li><a href="#" className="twitter"><i className="bi bi-twitter"></i></a></li>
              </ul>
              <h1 className={styles.title}>
                {/* Senior Front-end Developer */}
                Desenvolvedor Front-end Sênior
              </h1>
              <p className={styles.aboutText}>
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Cumque
                magni sit iusto eligendi vitae sint quibusdam debitis laboriosam
                quos, maxime quidem odit aperiam. Voluptatibus culpa iure
                dignissimos illum explicabo commodi.
              </p>

              <div className="link-group">
                <a href="#projects" className="btn">Projetos <i className="bi bi-arrow-right"></i></a>
                <a href="#" className="btn">Skills <i className="bi bi-arrow-right"></i></a>
              </div>
            </div>
          </div>

          <div className="projects" id="projects">
            {/* <h2 className="section-title">Projetos</h2> */}
            <ul className="projectsList">

              <li>
                <div className="projectItem">
                  <div className="projectInfo">
                    <h2 className="projectName">Almeida França</h2>
                    <p>Parceria com agência de marketing (Storica)</p>
                  </div>
                  <div className="projectLink">
                    <a href="#" className="btn">Ver projeto <i className="bi bi-arrow-right"></i></a>
                  </div>
                </div>
              </li>
              <li>
                <div className="projectItem">
                  <div className="projectInfo">
                    <h2 className="projectName">Wiz Soluções</h2>
                    <p>Parceria com agência de marketing (Storica)</p>
                  </div>
                  <div className="projectLink">
                    <a href="#" className="btn">Ver projeto <i className="bi bi-arrow-right"></i></a>
                  </div>
                </div>
              </li>
              <li>
                <div className="projectItem">
                  <div className="projectInfo">
                    <h2 className="projectName">Adde Valorem</h2>
                    <p>Parceria com agência de marketing (Storica)</p>
                  </div>
                  <div className="projectLink">
                    <a href="#" className="btn">Ver projeto <i className="bi bi-arrow-right"></i></a>
                  </div>
                </div>
              </li>
              <li>
                <div className="projectItem">
                  <div className="projectInfo">
                    <h2 className="projectName">Toda Eu Blog</h2>
                    <p>Portal do mundo feminino focado em Maquiagem</p>
                  </div>
                  <div className="projectLink">
                    <a href="#" className="btn">Ver projeto <i className="bi bi-arrow-right"></i></a>
                  </div>
                </div>
              </li>
              

            </ul>
          </div>
        </main>
      </div>
    </div>
  );
};

export default Home;
